### ISSUE TITLE
Please don't use _ to prefix private methods

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java#13]
In NativeUtils.java some private methods are prefixed with _. While prefixes in general are a matter of personal taste I do think it's important for Couchbase to be consistent. This pattern isn't used anywhere else. So please don't introduce it now unless you want to introduce it everywhere. Otherwise you confuse poor innocent devs like me. :)

**Comment by pasin** [comment]
This issue is fixed as part of moving to use couchbase-lite-java-sqlcipher instead of couchbase-lite-native.
