### ISSUE TITLE
Investigate growing memory on long running pull replication

### ISSUE THREAD

**Issue by march44** [couchbase/couchbase-lite-java#23]
For a 50minute Pull Repl test of 3.6Million documents, portable Java starts at 183MBytes memory and steadily raises to 204MBytes memory by the end. 

Investigate this further to see if there is a memory leak.

**Comment by hideki** [comment]
Hi @march44 
I recently worked for memory issue during pull replication.
https://github.com/couchbase/couchbase-lite-java-core/issues/447

If you have time and still have test environment, can you test this with master branch?

**Comment by tleyden** [comment]
I think we should proactively close this (in the name of reducing issue noise), and re-open it if problems are still seen.
