### ISSUE TITLE
Please add Java to CI!

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java#32]
So I can be 100% sure that whatever CI you are using it doesn't run the Java tests before allowing couchbase-lite-android to check in because the build.gradle file for Android contained the reference for the mock web server but the build.gradle for Java didn't and so everything broke. Please, Please, Please, don't treat Java as a second class citizen. The Java tests ARE the Android tests so anyone trying to check in anything in Android MUST make sure they haven't broken Java either. So please, can you set up the CI to make sure that both are tested!
   Thanks!

**Comment by hideki** [comment]
CBL Java is built on jenkins.
