### ISSUE TITLE
getAttachment() does not return null while getAttachmentNames() is empty

### ISSUE THREAD

**Issue by jmigot** [couchbase/couchbase-lite-java#33]
Hi,

There might be an issue with attachments, to reproduce the bug you have to save an attachment within a new revision, delete it and then try to access it:

1) Add a new photo attachment
```java
UnsavedRevision rev = entity.getDocument().getCurrentRevision().createRevision();
rev.setAttachment("photo.jpg", "image/jpeg", bitmap);
rev.save();
```

2) Then delete it:
```java
UnsavedRevision rev = entity.getDocument().getCurrentRevision().createRevision();
rev.removeAttachment("photo.jpg");
SavedRevision srev = rev.save();
```
3) Try to access attachment properties
```java
Log(srev.getAttachmentNames().toString());
Log(srev.getAttachment("photo.jpg").toString());
```
4) You get
```java
[]
com.couchbase.lite.Attachment@42386d30
```

So you get an empty list, however if you try to retrieve the specific attachment "photo.jpg", it doesn't return null as expected. There was only one reference to this photo and it has been deleted with the remove() method. Restarting the application seems to refresh the properties.

Thanks in advance

**Comment by hideki** [comment]
duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/218 And issue was already addressed.
