### ISSUE TITLE
Intermitment Null Pointer Exception in ChangeTracker.stopped

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java#39]
I've seen this fail a few times. But it's not a 100% repo. The last time I saw it I was running a formal test run and so have the stack available https://gist.github.com/yaronyg/597aae367de0ac569b6b

**Comment by hideki** [comment]
This issue will be tracked by CBL Java Core
https://github.com/couchbase/couchbase-lite-java-core/issues/317

**Comment by hideki** [comment]
Fix for couchbase/couchbase-lite-java-core#317 was merged. I will close this ticket.
