### ISSUE TITLE
Intermitment hang & Null Pointer Exceptions in ApiTest/testLiveQueryRun()

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-java#40]
When I run all the tests in couchbase-lite-java on Windows I will sometimes run in a situation where testLiveQueryRun in ApiTest will just hang. The failure log is available at https://gist.github.com/yaronyg/b8fa8220bafc0dccfec0

Note the two null exceptions at the end.

If I run the test by itself I will get one of those two null pointer exceptions, but not the other and the test passes. See https://gist.github.com/yaronyg/86663407e39200747a98 for an example of a passing log.

In debugging I did notice that the callback handler for a cursor was called after the JUnit tear down had been called and as a consequence it was getting null for database and thus threw a null pointer exception. But that shouldn't cause the test to hang.

Am I the only person seeing this or is this ringing any bells?

**Comment by hideki** [comment]
this ticket is duplicate with https://github.com/couchbase/couchbase-lite-java-core/issues/296 . Once java-core 296 is solved, close this ticket too.
