### ISSUE TITLE
Generate a replication digest, with the replicated ids added to the replication progress events?

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-java#58]
I was wondering, 
How nice would it be, to have the list of ids for the replicated documents, in addition to the current .completedCount and .totalCount properties?

Unfortunately I've started working with CBLite just a week ago, so I'm a little bit clueless about where to start looking for this information. 
Does anybody have any suggestions?

**Comment by hideki** [comment]
Hi @vbenso,

Replication.ChangeListener does not maintain replicated documents. You can obtain updated document Ids by Database.ChangeListener. See below sample. 

Example:
```
        database.addChangeListener(new Database.ChangeListener() {
            @Override
            public void changed(Database.ChangeEvent event) {
                Log.e(TAG, "Pull DB Event: " + event);
                List<DocumentChange> changes = event.getChanges();
                for(DocumentChange change:changes){
                    Log.e(TAG, change.toString());
                    Log.e(TAG, pullDB.getDocument(change.getDocumentId()).getProperties().toString());
                }
            }
        });
```

Hope this helps you.

Cheers!

**Comment by vbenso** [comment]
Very helpful indeed.
Thanks a lot.
