### ISSUE TITLE
IllegalArgumentException: Invalid database name: foward:slash after update to the latest cblite version

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-java#62]
with https://github.com/couchbase/couchbase-lite-android-liteserv/commit/8f2f7135994ae788b6ec8c4f5159a8bd00163cd1

in our cblite functional tests we have cases where we check db names https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-database.js#L62

recently 'foward/slash' was a valid db name in cblite(iOS/android). Now when I start  couchbase-lite-android-liteserv with the latest code I get 
``
E/libEGL  (   55): called unimplemented OpenGL ES API
W/WindowManager(  373): Screenshot failure taking screenshot for (328x546) to layer 21005
D/AndroidRuntime( 1267): Shutting down VM
D/dalvikvm( 1267): GC_CONCURRENT freed 96K, 15% free 586K/684K, paused 2ms+3ms, total 25ms
I/ActivityManager(  373): Start proc com.couchbase.liteservandroid for activity com.couchbase.liteservandroid/.MainActivity: pid=1278 uid=10053 gids={50053, 3003}
D/dalvikvm( 1278): Not late-enabling CheckJNI (already on)
D/dalvikvm( 1278): GC_CONCURRENT freed 237K, 9% free 3120K/3424K, paused 5ms+4ms, total 63ms
E/LiteServ( 1278): Error starting LiteServ
E/LiteServ( 1278): java.lang.IllegalArgumentException: Invalid database name: foward:slash
E/LiteServ( 1278): 	at com.couchbase.lite.Manager.getDatabase(Manager.java:372)
E/LiteServ( 1278): 	at com.couchbase.lite.Manager.upgradeDatabase(Manager.java:625)
E/LiteServ( 1278): 	at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:607)
E/LiteServ( 1278): 	at com.couchbase.lite.Manager.<init>(Manager.java:112)
E/LiteServ( 1278): 	at com.couchbase.liteservandroid.MainActivity.startCBLite(MainActivity.java:95)
E/LiteServ( 1278): 	at com.couchbase.liteservandroid.MainActivity.startCBLListener(MainActivity.java:73)
E/LiteServ( 1278): 	at com.couchbase.liteservandroid.MainActivity.onCreate(MainActivity.java:42)
E/LiteServ( 1278): 	at android.app.Activity.performCreate(Activity.java:5231)
E/LiteServ( 1278): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/LiteServ( 1278): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
E/LiteServ( 1278): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/LiteServ( 1278): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/LiteServ( 1278): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/LiteServ( 1278): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/LiteServ( 1278): 	at android.os.Looper.loop(Looper.java:136)
E/LiteServ( 1278): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/LiteServ( 1278): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/LiteServ( 1278): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/LiteServ( 1278): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/LiteServ( 1278): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/LiteServ( 1278): 	at dalvik.system.NativeStart.main(Native Method)
D/gralloc_goldfish( 1278): Emulator without GPU emulation detected.
I/ActivityManager(  373): Displayed com.couchbase.liteservandroid/.MainActivity: +1s847ms
I/ProcessStatsService(  373): Prepared write state in 6ms
```

**Comment by hideki** [comment]
This issue is no longer reproducible with CBL 1.2.0.
Forward-slash "/" is substituted with colon ":".
