### ISSUE TITLE
Support for Geographical Queries?

### ISSUE THREAD

**Issue by fakeh** [couchbase/couchbase-lite-java#63]
Hi all,

It seems https://github.com/couchbase/couchbase-lite-ios/wiki/Geo-Querying didn't make it into the main documentation for iOS? Is that feature still available there? Any plans to support in Java?

Would be great!
Thanks for your great work,
Dan.

**Comment by hideki** [comment]
Hi @fakeh,
https://github.com/couchbase/couchbase-lite-android/issues/221
Thanks,
Hideki
