### ISSUE TITLE
Help!!! Can not build couchbase lite java on centos 6.5

### ISSUE THREAD

**Issue by hitales** [couchbase/couchbase-lite-java#88]
Help!!! I can not build couchbase lite java on centos 6.5, the output as below:

:libraries:couchbase-lite-java-native:sqlite-custom:linkLinux_x86CbljavasqlitecustomSharedLibrary
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: ld 返回 1

**Comment by hideki** [comment]
Hi @hitales,

Is your platform is 32bit?

You might need to install followings.
```
$ sudo apt-get install gcc-multilib
$ sudo apt-get install g++-multilib
```

Or, please download CBL Java package from http://www.couchbase.com/nosql-databases/downloads

Thanks,

**Comment by hitales** [comment]
My platform is centos 6.5, there is not "apt-get",  while i use yum install:

[root@iZ23pdpwl83Z couchbase-lite-java]# yum install g++-multilib
Loaded plugins: security
Setting up Install Process
No package g++-multilib available.
Error: Nothing to do
[root@iZ23pdpwl83Z couchbase-lite-java]# yum install gcc-multilib
Loaded plugins: security
Setting up Install Process
No package gcc-multilib available.
Error: Nothing to do

There is not such packages!

according the last two lines error:
/usr/bin/ld: skipping incompatible /usr/lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++

it seems the stdc++ is not compatible, so where can i find the compatible lib?

Is this http://developer.couchbase.com/documentation/server/4.0/sdks/java-2.2/download-links.html the CBL Java package?

Thanks in advance!

**Comment by hideki** [comment]
>Is this http://developer.couchbase.com/documentation/server/4.0/sdks/java-2.2/download-links.html the CBL Java package?

Couchbase Server SDK and Couchbase Lite for Java is independent library. If you are looking for SDK to access Couchbase server with Java, Couchbase Server SDK for Java is right choice. If you are looking for Mobile database with sync functionality, Couchbase Lite for Java is correct choice.

For compilation error:
I guess your Centos is 64bit, and you are seeing error for 32 bit library comppilation. I think you can disable the compile for 32bit (x86) by commented out following line.
https://github.com/couchbase/couchbase-lite-java-native/blob/master/sqlite-custom/build-java.gradle#L133

Hope this helps you.

**Comment by hideki** [comment]
CBL Java v1.2.0 should contain Linux binary. Please try it. But this is built on Ubuntu. I am not sure if it works on CentOS.
- http://www.couchbase.com/dl/releases/couchbase-lite/java/1.2.0/couchbase-lite-java-1.2.0-community.zip
- http://www.couchbase.com/dl/releases/couchbase-lite/java/1.2.0/couchbase-lite-java-1.2.0-enterprise.zip

**Comment by zgramana** [comment]
Please let us know if you still have problems.
